/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package au.com.seek.aips;

public class App {
  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }

  String getGreeting() {
    return "Hello World!";
  }
}
